config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :holdings
  resources :stocks
  resources :portfolios

  root :to => "portfolios#index"
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '*path' => redirect('/')
  

end

app/models/holding.rb
class Holding < ActiveRecord::Base
  belongs_to :portfolio
  belongs_to :stock
  validates :stock, presence: true, allow_nil: false
  validates :portfolio, presence: true, allow_nil: false
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  before_filter :authorize
  before_action :set_holding, only: [:show, :edit, :update, :destroy]

  # GET /holdings
  # GET /holdings.json
  def index
    @holdings = Holding.where(portfolio_id: params[:portfolio_id])

  end

  # GET /holdings/1
  # GET /holdings/1.json
  def show

  end

  # GET /holdings/new
  def new
    @holding = Holding.new
  end

  # GET /holdings/1/edit
  def edit

  end

  # POST /holdings
  # POST /holdings.json
  def create
    @holding = Holding.new(holding_params)

    respond_to do |format|
      if @holding.save
        format.html { redirect_to @holding, notice: 'Holding was successfully created.' }
        format.json { render :show, status: :created, location: @holding }
      else
        format.html { render :new }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holdings/1
  # PATCH/PUT /holdings/1.json
  def update
    respond_to do |format|
      if @holding.update(holding_params)
        format.html { redirect_to @holding, notice: 'Holding was successfully updated.' }
        format.json { render :show, status: :ok, location: @holding }
      else
        format.html { render :edit }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holdings/1
  # DELETE /holdings/1.json
  def destroy
    @holding.destroy
    respond_to do |format|
      format.html { redirect_to holdings_url, notice: 'Holding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holding
      @holding = Holding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holding_params
      params.require(:holding).permit(:portfolio_id, :stock_id, :quantity)
    end
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/views/holdings/_form.html.erb
<%= form_for @holding, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :portfolio_id, :class => 'control-label' %>
    <div class="controls">

      <%= f.text_field :portfolio_id, :class => 'text_field' %>

    </div>
  </div>
  <div class="control-group">
    <%= f.label :stock_id, :class => 'control-label' %>
    <div class="controls">

      <%= f.text_field :stock_id, :class => 'text_field' %>

    </div>
  </div>
  <div class="control-group">
    <%= f.label :quantity, :class => 'control-label' %>
    <div class="controls">

      <%= f.text_field :quantity, :class => 'text_field' %>

    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                holdings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/holdings/edit.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/holdings/index.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("models.holding.id", :default => model_class.human_attribute_name(:id)) %></th>
      <th><%= t("models.holding.portfolio_id", :default => model_class.human_attribute_name(:portfolio_id)) %></th>
      <th><%= t("models.holding.stock_id", :default => model_class.human_attribute_name(:stock_id)) %></th>
      <th><%= t("models.holding.quantity", :default => model_class.human_attribute_name(:quantity)) %></th>
      <th><%= t("models.holding.price") %></th>
      <th><%= t("models.holding.created_at", :default => model_class.human_attribute_name(:created_at)) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @holdings.each do |holding| %>
      <tr>
        <td><%= link_to holding.id, holding_path(holding) %></td>
        <td><%= holding.portfolio.name if holding.portfolio %></td>
        <td><%= holding.stock.symbol if holding.stock %></td>
        <td><%= holding.quantity %></td>
        <td><%= holding.quantity * holding.stock.price %></td>
        <td><%= holding.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_holding_path(holding), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      holding_path(holding),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_holding_path,
            :class => 'btn btn-primary' %>

app/views/holdings/new.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/holdings/show.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:portfolio_id) %>:</strong></dt>
  <dd><%= @holding.portfolio_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock_id) %>:</strong></dt>
  <dd><%= @holding.stock_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @holding.quantity %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              holdings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_holding_path(@holding), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              holding_path(@holding),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>