config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :holdings
  resources :stocks
  resources :portfolios

  root :to => "portfolios#index"
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '*path' => redirect('/')
  

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates :symbol, presence: true
  has_many :portfolios, :through => :holdings
  has_many :holdings

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_filter :authorize
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all

  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show

  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit

  end

  # POST /stocks
  # POST /stocks.json
  def create

    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:symbol, :name, :price)
    end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for @stock, :html => { :class => "form-horizontal stock" } do |f| %>

  <% if @stock.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @stock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :symbol, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :symbol, :class => 'form-control' %>
    </div>
    <%=f.error_span(:symbol) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stocks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/stocks/edit.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stocks/index.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("models.stock.id", :default => model_class.human_attribute_name(:id)) %></th>
      <th><%= t("models.stock.symbol", :default => model_class.human_attribute_name(:symbol)) %></th>
      <th><%= t("models.stock.name", :default => model_class.human_attribute_name(:name)) %></th>
      <th><%= t("models.stock.price", :default => model_class.human_attribute_name(:price)) %></th>
      <th><%= t("models.stock.created_at", :default => model_class.human_attribute_name(:created_at)) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to stock.id, stock_path(stock) %></td>
        <td><%= stock.symbol %></td>
        <td><%= stock.name %></td>
        <td><%= stock.price %></td>
        <td><%= stock.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_stock_path(stock), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      stock_path(stock),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_stock_path,
            :class => 'btn btn-primary' %>

app/views/stocks/new.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stocks/show.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:symbol) %>:</strong></dt>
  <dd><%= @stock.symbol %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @stock.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @stock.price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              stocks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_stock_path(@stock), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              stock_path(@stock),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>